name: CI Base

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'

jobs:
  gitHubInfos:
    name: Get GitHub infos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Display GitHub Context
        id: ghdetails
        run: |
          echo "=== GitHub Context ==="
          echo "${{ toJson(github) }}"
