name: CI Dockerize

on:
    workflow_run:
      workflows: ["CI Tests"]
      types:
        - completed

jobs:
  dockerize:
        name: Build and Push Docker Image
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              id: checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}

            - name: Build Docker image
              id: build-image
              run: |
                docker build -t garnier_andrew_exchange:latest .

            - name: Push Docker image to Docker Hub
              id: push-image
              env:
                DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
                DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
              run: |
                echo $DOCKER_HUB_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
                docker tag garnier_andrew_exchange:latest $DOCKER_HUB_USERNAME/garnier_andrew_exchange:latest
                docker push $DOCKER_HUB_USERNAME/garnier_andrew_exchange:latest